# Generated by Django 5.0.1 on 2025-07-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verify', 'Tekshirish'), ('download', 'Yuklab olish'), ('share', 'Ulashish'), ('view', "Ko'rish")], max_length=20, verbose_name='Harakat')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Tafsilotlar')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='certificates.certificate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tekshiruv logi',
                'verbose_name_plural': 'Tekshiruv loglari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_ip', models.GenericIPAddressField(verbose_name="So'rovchi IP")),
                ('requester_user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('requester_email', models.EmailField(blank=True, max_length=254, verbose_name="So'rovchi email")),
                ('requester_organization', models.CharField(blank=True, max_length=255, verbose_name="So'rovchi tashkilot")),
                ('verification_result', models.BooleanField(default=True, verbose_name='Tekshiruv natijasi')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Tekshiruv vaqti')),
                ('verification_method', models.CharField(default='web', max_length=50, verbose_name='Tekshiruv usuli')),
                ('verification_location', models.CharField(blank=True, max_length=255, verbose_name='Joylashuv')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='certificates.certificate')),
            ],
            options={
                'verbose_name': "Tekshiruv so'rovi",
                'verbose_name_plural': "Tekshiruv so'rovlari",
                'ordering': ['-verification_date'],
            },
        ),
    ]
