# Generated by Django 5.0.1 on 2025-07-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_certificates', models.IntegerField(default=0)),
                ('new_certificates', models.IntegerField(default=0)),
                ('verified_certificates', models.IntegerField(default=0)),
                ('total_organizations', models.IntegerField(default=0)),
                ('active_organizations', models.IntegerField(default=0)),
                ('total_verifications', models.IntegerField(default=0)),
                ('successful_verifications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tizim statistikasi',
                'verbose_name_plural': 'Tizim statistikalari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_certificates', models.IntegerField(default=0)),
                ('verified_certificates', models.IntegerField(default=0)),
                ('pending_certificates', models.IntegerField(default=0)),
                ('revoked_certificates', models.IntegerField(default=0)),
                ('certificates_this_month', models.IntegerField(default=0)),
                ('verifications_this_month', models.IntegerField(default=0)),
                ('total_verifications', models.IntegerField(default=0)),
                ('successful_verifications', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard statistikasi',
                'verbose_name_plural': 'Dashboard statistikalari',
            },
        ),
    ]
