# Generated by Django 5.0.1 on 2025-07-20 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField(unique=True, verbose_name='Blok raqami')),
                ('block_hash', models.CharField(max_length=66, unique=True, verbose_name='Blok hash')),
                ('parent_hash', models.CharField(max_length=66, verbose_name='Ota-blok hash')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt belgisi')),
                ('miner', models.CharField(max_length=42, verbose_name='Miner')),
                ('difficulty', models.BigIntegerField(default=1000000, verbose_name='Qiyinchilik')),
                ('gas_limit', models.BigIntegerField(default=8000000, verbose_name='Gaz limiti')),
                ('gas_used', models.BigIntegerField(default=0, verbose_name='Ishlatilgan gaz')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Tranzaksiyalar soni')),
                ('transactions_root', models.CharField(max_length=66, verbose_name='Tranzaksiyalar root')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blokcheyn bloki',
                'verbose_name_plural': 'Blokcheyn bloklari',
                'ordering': ['-block_number'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('contract_type', models.CharField(choices=[('certificate_registry', 'Sertifikat reestri'), ('organization_registry', 'Tashkilot reestri'), ('verification_contract', 'Tekshiruv kontrakti')], max_length=30, verbose_name='Turi')),
                ('address', models.CharField(max_length=42, unique=True, verbose_name='Kontrakt manzili')),
                ('abi', models.JSONField(default=list, verbose_name='ABI')),
                ('bytecode', models.TextField(blank=True, verbose_name='Bytecode')),
                ('source_code', models.TextField(blank=True, verbose_name='Manba kodi')),
                ('deployment_transaction', models.CharField(blank=True, max_length=66, verbose_name='Deploy tranzaksiyasi')),
                ('deployment_block', models.BigIntegerField(blank=True, null=True, verbose_name='Deploy bloki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart kontrakt',
                'verbose_name_plural': 'Smart kontraktlar',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=66, unique=True, verbose_name='Tranzaksiya hash')),
                ('block_number', models.BigIntegerField(blank=True, null=True, verbose_name='Blok raqami')),
                ('block_hash', models.CharField(blank=True, max_length=66, verbose_name='Blok hash')),
                ('transaction_type', models.CharField(choices=[('certificate_issue', 'Sertifikat chiqarish'), ('certificate_verify', 'Sertifikat tasdiqlash'), ('certificate_revoke', 'Sertifikat bekor qilish'), ('certificate_transfer', "Sertifikat o'tkazish")], max_length=30, verbose_name='Tranzaksiya turi')),
                ('from_address', models.CharField(max_length=42, verbose_name='Yuboruvchi manzil')),
                ('to_address', models.CharField(blank=True, max_length=42, verbose_name='Qabul qiluvchi manzil')),
                ('transaction_data', models.JSONField(default=dict, verbose_name="Tranzaksiya ma'lumotlari")),
                ('gas_used', models.BigIntegerField(default=21000, verbose_name='Ishlatilgan gaz')),
                ('gas_price', models.BigIntegerField(default=20000000000, verbose_name='Gaz narxi')),
                ('transaction_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name="Tranzaksiya to'lovi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan')),
                ('confirmations', models.IntegerField(default=0, verbose_name='Tasdiqlar soni')),
                ('required_confirmations', models.IntegerField(default=12, verbose_name='Kerakli tasdiqlar')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Blokcheyn tranzaksiyasi',
                'verbose_name_plural': 'Blokcheyn tranzaksiyalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_hash'], name='blockchain__transac_697a0b_idx'), models.Index(fields=['certificate', 'status'], name='blockchain__certifi_989f40_idx'), models.Index(fields=['block_number'], name='blockchain__block_n_035750_idx')],
            },
        ),
    ]
