# Generated by Django 5.0.1 on 2025-07-20 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi')),
                ('organization_type', models.CharField(choices=[('university', 'Universitet'), ('college', 'Kollej'), ('institute', 'Institut'), ('academy', 'Akademiya'), ('school', 'Maktab'), ('training_center', "O'quv markazi"), ('certification_body', 'Sertifikatlashtirish organi'), ('government', 'Davlat muassasasi'), ('private', 'Xususiy tashkilot')], max_length=50, verbose_name='Turi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('country', models.CharField(default="O'zbekiston", max_length=100, verbose_name='Mamlakat')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Litsenziya raqami')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Soliq ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name="Ro'yxat raqami")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Tashkil etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_users', models.ManyToManyField(blank=True, related_name='administered_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('issuer', 'Sertifikat chiqaruvchi'), ('viewer', "Ko'ruvchi")], default='viewer', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tashkilot a'zoligi",
                'verbose_name_plural': "Tashkilot a'zoliklari",
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
