# Generated by Django 5.0.1 on 2025-07-20 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=50, unique=True, verbose_name='Sertifikat ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('certificate_type', models.CharField(choices=[('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('license', 'Litsenziya'), ('award', 'Mukofot')], default='certificate', max_length=20, verbose_name='Turi')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Muassasa nomi')),
                ('institution_address', models.TextField(blank=True, verbose_name='Muassasa manzili')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Daraja/Kurs')),
                ('field_of_study', models.CharField(blank=True, max_length=255, verbose_name="Ta'lim yo'nalishi")),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Baho')),
                ('issue_date', models.DateField(verbose_name='Chiqarilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('issued', 'Chiqarilgan'), ('verified', 'Tasdiqlangan'), ('revoked', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat fayli')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR kod')),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, verbose_name='Blokcheyn hash')),
                ('blockchain_transaction', models.CharField(blank=True, max_length=255, verbose_name='Tranzaksiya ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Chiqaruvchi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shablon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('template_file', models.FileField(upload_to='templates/', verbose_name='Shablon fayli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Sertifikat shabloni',
                'verbose_name_plural': 'Sertifikat shablonlari',
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_ip', models.GenericIPAddressField(verbose_name='Tekshiruvchi IP')),
                ('verifier_user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Tekshiruv vaqti')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Haqiqiy')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Sertifikat tekshiruvi',
                'verbose_name_plural': 'Sertifikat tekshiruvlari',
                'ordering': ['-verification_date'],
            },
        ),
    ]
