# Generated by Django 5.0.1 on 2025-07-17 21:21


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [

        ('accounts', '0001_initial'),

    ]

    operations = [

        migrations.RenameField(

            model_name='user',

            old_name='organization_license',

            new_name='institution_license',

        ),

        migrations.RemoveField(

            model_name='user',

            name='organization_address',

        ),

        migrations.RemoveField(

            model_name='user',

            name='organization_name',

        ),

        migrations.AddField(

            model_name='user',

            name='institution_address',

            field=models.TextField(blank=True, verbose_name='Muassasa manzili'),

        ),

        migrations.AddField(

            model_name='user',

            name='institution_name',

            field=models.CharField(blank=True, max_length=255, verbose_name='Muassasa nomi'),

        ),

        migrations.AlterField(

            model_name='user',

            name='role',

            field=models.CharField(choices=[('student', 'Talaba'), ('admin', 'Muassasa Administratori'),
                                            ('superadmin', 'Super Administrator'), ('checker', 'Tekshiruvchi')],
                                   default='student', max_length=20, verbose_name='Rol'),

        ),

    ]
