name: CerifyNow CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  django_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test

  deploy_django:
    runs-on: ubuntu-latest
    needs: django_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu
            REPO_DIR="CerifyNow"

            if [ ! -d "$REPO_DIR" ]; then
              echo "📦 Cloning repository..."
              git clone https://github.com/CerifyNow/CerifyNow-API-v1.git $REPO_DIR
            else
              echo "🔄 Pulling latest changes..."
              cd $REPO_DIR
              git pull origin main
              cd ..
            fi

            cd /home/ubuntu/$REPO_DIR

            
            echo "🐍 Creating virtual environment..."
            python3 -m venv venv || python -m venv venv || { echo "❌ Venv yaratib bo‘lmadi"; exit 1; }
            
            if [ ! -f "venv/bin/activate" ]; then
               echo "❌ venv yaratishda muammo bor, activate fayli topilmadi"
               exit 1
            fi
            
            echo "⚙️ Activating virtual environment..."
            source venv/bin/activate

            echo "📦 Installing dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt

            echo "🧬 Running migrations..."
            python manage.py migrate --noinput

            echo "🎨 Collecting static files..."
            python manage.py collectstatic --noinput

            echo "🚀 Restarting Django service..."
            sudo systemctl daemon-reload
            sudo systemctl restart cerifynow.service

            echo "✅ Deployment complete!"
